### ISSUE TITLE
TypeError Help

### ISSUE THREAD

**Issue by bennettnw2** [nsebhastian/react-node-postgres#1]
Hello,  I am not sure if this is on my end or not but I cloned your repo and when I ran it, I got this error.
```text
/Users/bennettnw2/Workspace/React/postgresDeleteme/react-node-postgres/node-postgres/merchant_model.js:17
      resolve(results.rows);
                      ^

TypeError: Cannot read property 'rows' of undefined
    at /Users/bennettnw2/Workspace/React/postgresDeleteme/react-node-postgres/node-postgres/merchant_model.js:17:23
    at PendingItem.callback (/Users/bennettnw2/Workspace/React/postgresDeleteme/react-node-postgres/node-postgres/node_modules/pg-pool/index.js:327:16)
    at /Users/bennettnw2/Workspace/React/postgresDeleteme/react-node-postgres/node-postgres/node_modules/pg-pool/index.js:229:23
    at Connection.connectingErrorHandler (/Users/bennettnw2/Workspace/React/postgresDeleteme/react-node-postgres/node-postgres/node_modules/pg/lib/client.js:194:14)
    at Connection.emit (events.js:311:20)
    at Socket.<anonymous> (/Users/bennettnw2/Workspace/React/postgresDeleteme/react-node-postgres/node-postgres/node_modules/pg/lib/connection.js:134:12)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
```

Could you test this out to see if it still works?

**Comment by NathanSebhastian** [comment]
Hi, do you have any data inside your merchants table? That error is because `getMerchants` function is called but the table has no data

**Comment by bennettnw2** [comment]
Ah, ok.  I do not.  Let me check that out in a bit.  Thanks!

**Comment by bennettnw2** [comment]
Ok, so I have some type of connection error totally on my side.  I'll post my problem and solution once I figure it out.  Thanks for your tutorial!

**Comment by bennettnw2** [comment]
I did not pinpoint the problem but I suspect the problem was just a mess with my configured settings to properly access the database.  I simply started over and was successful this time around.  Thanks for a great tutorial!
